-- Create tables for HR Module System

-- Jobs table
CREATE TABLE jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  department TEXT NOT NULL,
  description TEXT NOT NULL,
  requirements TEXT NOT NULL,
  salary TEXT,
  location TEXT,
  posted_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Applications table
CREATE TABLE applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id BIGINT REFERENCES jobs(id) ON DELETE SET NULL,
  job_title TEXT NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  experience TEXT NOT NULL,
  cover_letter TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'received',
  workflow TEXT[] DEFAULT ARRAY['received'],
  submitted_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE applications ENABLE ROW LEVEL SECURITY;

-- Policies for jobs table (public read, admin write)
CREATE POLICY "Jobs are viewable by everyone" 
ON jobs FOR SELECT USING (true);

CREATE POLICY "Anyone can insert jobs" 
ON jobs FOR INSERT WITH CHECK (true);

CREATE POLICY "Anyone can update jobs" 
ON jobs FOR UPDATE USING (true);

CREATE POLICY "Anyone can delete jobs" 
ON jobs FOR DELETE USING (true);

-- Policies for applications table (public read/write)
CREATE POLICY "Applications are viewable by everyone" 
ON applications FOR SELECT USING (true);

CREATE POLICY "Anyone can insert applications" 
ON applications FOR INSERT WITH CHECK (true);

CREATE POLICY "Anyone can update applications" 
ON applications FOR UPDATE USING (true);

CREATE POLICY "Anyone can delete applications" 
ON applications FOR DELETE USING (true);

-- Create indexes for better performance
CREATE INDEX idx_jobs_posted_date ON jobs(posted_date DESC);
CREATE INDEX idx_applications_status ON applications(status);
CREATE INDEX idx_applications_job_id ON applications(job_id);
CREATE INDEX idx_applications_submitted_date ON applications(submitted_date DESC);
